### PR TITLE
decompile all tslrcm/vanilla k2 scripts with DeNCS

### PR DESCRIPTION
**Pull request by th3w1zard1**
I notice you're missing most of the k2 scripts, here are the ones I was able to decompile with DeNCS.

Please note:
- The modified DeNCS version I used does not ensure accuracy, just ensures that at least partials were outputted.
- This was done on the Steam version of K2, Aspyr patch, and TSLRCM installed.
- This took my i7-7800k running at 100% processor usage about 4 hours to do, so if any changes are requested please build up a large list of changes to make to my batch process to limit the number of times I will need to do this. (e.g. foldername format or decompiling without tslrcm)
- If you wish to move the folders around, I highly recommend using `git mv` due to the massive number of files. Moving them in explorer will cause github to say they were deleted and new files created, doubling your commit and preventing commit history from working.

### CODE REVIEW

**Comment by JCarter426** [comment]
This is not intended to include TSLRCM.

**Comment by oldrepublicwizard** [comment]
@JCarter426 your repo structure says otherwise?
image

**Comment by JCarter426** [comment]
The folders are placeholders. As far as I recall, no decompiled scripts for KOTOR 2 have been added yet, only the source scripts included in the game. However, the intent is not to mix the original game and TSLRCM, as your pull request does.

**Comment by DarthParametric** [comment]
> As far as I recall, no decompiled scripts for KOTOR 2 have been added yet

All the vanilla TSL scripts (that you batch decompiled and supplied) have already been added.


> the intent is not to mix the original game and TSLRCM

The original intent _was_ to include TSLRCM, but that was before we migrated to a repo with "vanilla" in the name. We should probably create a second dedicated repo for TSLRCM source. Maybe under the DeadlyStream org? I believe zbyl2 already granted us permission to publicly host it.

**Comment by JCarter426** [comment]
> All the vanilla TSL scripts (that you batch decompiled and supplied) have already been added.

The TSLRCM folder doesn't have these.

> The original intent was to include TSLRCM, but that was before we migrated to a repo with "vanilla" in the name.

Not what I meant. Look at the commit history. It doesn't add anything to either place and instead makes a new, jumbled folder. As a result, it includes multiple copies of some scripts, one from TSLRCM that is used and one from the original game that unused when TSLRCM is installed and is already in the other source folder.

**Comment by oldrepublicwizard** [comment]
The objective was initially to integrate the TSLRCM updates, followed by the original (vanilla) versions, and then to incorporate the Aspyr modifications. The strategy involved leveraging Git's capabilities to identify and analyze overlaps and distinctions among the script versions.

The oversight occurred in not utilizing the 'create draft pull request' feature, which would have indicated that the pull request was in progress and not yet finalized. Implementing steps #3 and #2 will still facilitate this regardless

**Pull request closed without merging**
